# Generated by Django 2.1.7 on 2019-04-18 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moives',
            old_name='type',
            new_name='typee',
        ),
    ]
